version: '3'
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: phpconfig-docker
        ports:
            - 8080:80
        volumes:
            - .:/srv/app